# Generated by Django 4.2.3 on 2023-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='изображение'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='a',
        ),
    ]
